include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - empty_constructor_bodies
    - omit_local_variable_types
    - prefer_final_locals
    - prefer_single_quotes
    - sort_child_properties_last
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - unawaited_futures
    - use_full_hex_values_for_flutter_colors
