name: Dependencies Updater

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 2'

jobs:
  update_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Dependencies
        uses: peiffer-innovations/actions-dart-dependency-updater@v1
        with:
          merge: true
          paths: .,example
          pull_request: true
          token: ${{ secrets.REPO_TOKEN }}
